# Generated by Django 5.0.6 on 2024-06-07 19:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Principle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('principle_id', models.IntegerField()),
                ('title', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Strategy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name_plural': 'Strategies',
            },
        ),
        migrations.CreateModel(
            name='Descriptor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descriptor_id', models.IntegerField()),
                ('title', models.CharField(max_length=255)),
                ('content', models.TextField()),
                ('principle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='elama.principle')),
                ('strategy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='elama.strategy')),
            ],
        ),
        migrations.AddField(
            model_name='principle',
            name='strategy',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='elama.strategy'),
        ),
        migrations.CreateModel(
            name='Individual',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer', models.IntegerField()),
                ('confirmed', models.BooleanField(default=False)),
                ('user_id', models.IntegerField()),
                ('descriptor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='elama.descriptor')),
                ('principle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='elama.principle')),
                ('strategy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='elama.strategy')),
            ],
        ),
    ]
