# Generated by Django 5.0.6 on 2024-06-12 17:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Autoevaluacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_hora', models.DateTimeField()),
            ],
            options={
                'verbose_name_plural': 'Autoevaluaciones',
            },
        ),
        migrations.CreateModel(
            name='Entidad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
            ],
            options={
                'verbose_name_plural': 'Entidades',
            },
        ),
        migrations.CreateModel(
            name='Estrategia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Principio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('estrategia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='elama.estrategia')),
            ],
        ),
        migrations.CreateModel(
            name='Descriptor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('contenido', models.TextField()),
                ('principio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='elama.principio')),
            ],
            options={
                'verbose_name_plural': 'Descriptores',
            },
        ),
        migrations.CreateModel(
            name='Programa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('entidad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='elama.entidad')),
            ],
        ),
        migrations.CreateModel(
            name='Volcado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('respuesta', models.IntegerField()),
                ('autoevaluacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='elama.autoevaluacion')),
                ('descriptor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='elama.descriptor')),
            ],
        ),
    ]
